### ISSUE TITLE
Serializer

### ISSUE THREAD

**Issue by fullbl** [vinyvicente/doctrine-point-type#13]
Hi! Providing a normalizer for [symfony/serializer](https://symfony.com/doc/current/components/serializer.html) is outside the scope of this library? It is very simple, but it, of course, add dependencies on the serializer interfaces. Does it make sense to create it here? In another repo? Or does every user  implement it by himself?

I can provide my implementation, if needed!

**Comment by vinyvicente** [comment]
Feel free to PR, @fullbl :)

**Comment by fullbl** [comment]
Here you are!

**Comment by vinyvicente** [comment]
Thanks! Created on release 2.2.2

https://github.com/vinyvicente/doctrine-point-type/releases/tag/v2.2.2
