### ISSUE TITLE
¡TY FOR CREATING THIS!

### ISSUE THREAD

**Issue by nightywatcha** [vinyvicente/doctrine-point-type#17]
I tried to setup it myself using things like https://codeutopia.net/blog/2011/02/19/using-spatial-data-in-doctrine-2/ as source, but i was having problems with doctrine, as translation had quotation marks :s
```sql
...1, 1083, "POINT(19.420864 -99.167244)", "2021-09-27 04:00:42", "2021-09-27 04:00:42")
```

Hopefully your package works perfectly fine! So now i can keep focusing to adding points!

**Comment by vinyvicente** [comment]
Ok, good for you :)
