### ISSUE TITLE
SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field

### ISSUE THREAD

**Issue by r5b9** [vinyvicente/doctrine-point-type#6]
An exception occurred while executing 'INSERT INTO `point` (`address`, `coordinates`) VALUES(?, ?)' with params ["Test", "POINT(40.760381 -73.976683)"]:
SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field

I set it like this:
```
$obj = new Point();
$obj->setAddress('Test');
$obj->setCoordinates(new Point(40.7603807, -73.9766831));
$manager->persist($obj);
$manager->flush();
```

**Comment by vinyvicente** [comment]
Solved by #7
